fix(menu): restore missing closing brace in initializeSocialLinks
При удалении блока SwAssist в предыдущем коммите пропала
закрывающая скобка цепочки else-if, из-за чего падала сборка:
MainDrawer.java:84: error: illegal start of expression